name: Publish NPM Packages (Latest)

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release. patch or minor (major if breaking)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish-browser-agent-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.PAT_GITHUB }}

      - name: "Install and Build"
        run: npx lerna bootstrap && npm run packages:build

      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npx lerna version ${{ github.event.inputs.release_type }} --no-changelog --yes

          npx lerna publish from-package --no-verify-access --yes
